[project]
name = "ufpi-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyarrow>=21.0.0",
    "pyspark>=4.0.1",
    "requests>=2.32.5",
]
